
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taefaucixgmywrdwgtdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZWZhdWNpeGdteXdyZHdndGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMjc3NTMsImV4cCI6MjA1NjkwMzc1M30.No1WPUgWVHdLmK7SREP_ZO2Aj07LO3gfAEN4a7C16B8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
