// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpsynjeugfrclbegxqgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwc3luamV1Z2ZyY2xiZWd4cWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzU0NDgsImV4cCI6MjA1Njg1MTQ0OH0.RMyx9fFkCabV7auTer0k9srdB1D_ofai3V8q3P7L9Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);